CREATE TABLE `tharakan_monster_CC_npclog` (
`count`  int(255) UNSIGNED NOT NULL AUTO_INCREMENT ,
`num`  int(11) NOT NULL DEFAULT 0 ,
`select`  int(11) NOT NULL DEFAULT 0 ,
`date`  datetime NOT NULL ,
PRIMARY KEY (`count`)
)
ENGINE=MyISAM
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=1
CHECKSUM=0
ROW_FORMAT=DYNAMIC
DELAY_KEY_WRITE=0
;

